apiVersion: v1
kind: Service
metadata:
  name: whoami-lb-zeromatch
  labels:
    kubernetes.courselabs.co: services
    app: whoami
spec:
  selector:
    app: whoami
    label: wontmatch
  ports:
    - name: http
      port: 8081
      targetPort: 80
  type: LoadBalancer